// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmXDSsPALt30O9n5iMI20pTFxaL9ZP_00',
    appId: '1:1035990208726:web:61c78a15411764f064b977',
    messagingSenderId: '1035990208726',
    projectId: 'bary-solutions',
    authDomain: 'bary-solutions.firebaseapp.com',
    storageBucket: 'bary-solutions.appspot.com',
    measurementId: 'G-MNYYWW93KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqDcZ8U4RC2OwjS-jkcjyK9VHOoRaxRMM',
    appId: '1:1035990208726:android:172c40182352c54464b977',
    messagingSenderId: '1035990208726',
    projectId: 'bary-solutions',
    storageBucket: 'bary-solutions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJVEFqZEo6aMcEHBwM5BguRDrxww2jkyA',
    appId: '1:1035990208726:ios:0c9f2a0ad56fdd2664b977',
    messagingSenderId: '1035990208726',
    projectId: 'bary-solutions',
    storageBucket: 'bary-solutions.appspot.com',
    androidClientId: '1035990208726-hgm4ijhnnumcsmofbcvabh5hl7g5v3nt.apps.googleusercontent.com',
    iosClientId: '1035990208726-3tvuauqidkjgub66ffehs70mbd4th7en.apps.googleusercontent.com',
    iosBundleId: 'com.example.barySolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJVEFqZEo6aMcEHBwM5BguRDrxww2jkyA',
    appId: '1:1035990208726:ios:0c9f2a0ad56fdd2664b977',
    messagingSenderId: '1035990208726',
    projectId: 'bary-solutions',
    storageBucket: 'bary-solutions.appspot.com',
    androidClientId: '1035990208726-hgm4ijhnnumcsmofbcvabh5hl7g5v3nt.apps.googleusercontent.com',
    iosClientId: '1035990208726-3tvuauqidkjgub66ffehs70mbd4th7en.apps.googleusercontent.com',
    iosBundleId: 'com.example.barySolutions',
  );
}
